In [1]:
import numpy as np

In [27]:
np.__version__

'1.14.3'

In [10]:
np.array([1,2,3,4,5,6,7,8,9],dtype='float32')

array([1., 2., 3., 4., 5., 6., 7., 8., 9.], dtype=float32)

In [13]:
np.array([range(i,i+3) for i in [2,4,5]])

array([[2, 3, 4],
       [4, 5, 6],
       [5, 6, 7]])

In [14]:
np.zeros(10,dtype=int)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [16]:
np.ones((3,5),dtype=float)

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [18]:
np.arange(0,20,2) #creating a array from 0 to 20 in difference of 2


array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [19]:
np.linspace(0,1,5)# creating an array and fit it into the 0-1 linearly space by 5

array([0.  , 0.25, 0.5 , 0.75, 1.  ])

In [21]:
np.random.random((3,3))

array([[0.25314125, 0.13751087, 0.8901077 ],
       [0.29759576, 0.53702595, 0.60441205],
       [0.86298577, 0.63281654, 0.97655017]])

In [24]:
np.random.randint(0,10,(3,3)) #creating random array from 0 to 10 3 by 3 dimention

array([[2, 4, 7],
       [6, 1, 4],
       [6, 5, 2]])

In [26]:
np.eye(3)#creating identity matrix

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])